apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-runner
spec:
  template:
    spec:
      containers:
      - name: query-runner
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
      - name: jaeger-agent
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
