apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  template:
    spec:
        containers:
          - name: jaeger
            securityContext:
              # Required to prevent escalations to root.
              allowPrivilegeEscalation: false
              runAsUser: 100
              runAsGroup: 101
