apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntect-server
spec:
  template:
    spec:
      containers:
      - name: syntect-server
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 100
          runAsGroup: 101
