apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-store
spec:
  template:
    spec:
      containers:
      - name: redis-store
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 999
          runAsGroup: 1000
      - name: redis-exporter
        securityContext:
          # Required to prevent escalations to root.
          allowPrivilegeEscalation: false
          runAsUser: 999
          runAsGroup: 1000
